# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_image_store}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mitsuhiro Shibuya"]
  s.date = %q{2011-08-24}
  s.description = %q{Rails image storage plugin with multiple backend support}
  s.email = %q{mit.shibuya@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "acts_as_image_store.gemspec",
    "app/controllers/rails_admin/image_store_controller.rb",
    "app/controllers/stored_images_controller.rb",
    "app/models/stored_image.rb",
    "app/views/layouts/acts_as_image_store/_multiple_image.html.erb",
    "config/locales/en.yml",
    "config/locales/ja.yml",
    "config/routes.rb",
    "init.rb",
    "lib/acts_as_image_store.rb",
    "lib/acts_as_image_store/active_record.rb",
    "lib/acts_as_image_store/cache_adapters/abstract.rb",
    "lib/acts_as_image_store/cache_adapters/external.rb",
    "lib/acts_as_image_store/cache_adapters/file_system.rb",
    "lib/acts_as_image_store/cache_adapters/mogile_fs.rb",
    "lib/acts_as_image_store/cache_adapters/s3.rb",
    "lib/acts_as_image_store/engine.rb",
    "lib/acts_as_image_store/form_builder.rb",
    "lib/acts_as_image_store/image_deletable.rb",
    "lib/acts_as_image_store/rails_admin/image.rb",
    "lib/acts_as_image_store/rails_admin/multiple_image.rb",
    "lib/acts_as_image_store/storage_adapters/abstract.rb",
    "lib/acts_as_image_store/storage_adapters/database.rb",
    "lib/acts_as_image_store/storage_adapters/file_system.rb",
    "lib/acts_as_image_store/storage_adapters/mogile_fs.rb",
    "lib/acts_as_image_store/storage_adapters/s3.rb",
    "lib/acts_as_image_store/tag_helper.rb",
    "lib/acts_as_image_store/task.rb",
    "lib/acts_as_image_store/url_helper.rb",
    "lib/acts_as_image_store/validates_image_attribute.rb",
    "lib/rails/generators/acts_as_image_store/acts_as_image_store_generator.rb",
    "lib/rails/generators/acts_as_image_store/templates/image_store.yml",
    "lib/rails/generators/acts_as_image_store/templates/initializer.rb",
    "lib/rails/generators/acts_as_image_store/templates/migration.rb",
    "lib/rails/generators/acts_as_image_store/templates/schema.rb",
    "lib/tasks/acts_as_image_store.rake",
    "public/javascripts/acts_as_image_store.js",
    "spec/acts_as_image_store/validators/file_size_spec.rb",
    "spec/acts_as_image_store/validators/height_spec.rb",
    "spec/acts_as_image_store/validators/image_type_spec.rb",
    "spec/acts_as_image_store/validators/width_spec.rb",
    "spec/acts_as_image_store_spec.rb",
    "spec/cache_adapters_spec.rb",
    "spec/controllers/image_tests_controller_spec.rb",
    "spec/controllers/stored_images_controller_spec.rb",
    "spec/dummy/Rakefile",
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/controllers/confirms_controller.rb",
    "spec/dummy/app/controllers/image_tests_controller.rb",
    "spec/dummy/app/controllers/multiples_controller.rb",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/app/helpers/confirms_helper.rb",
    "spec/dummy/app/helpers/image_tests_helper.rb",
    "spec/dummy/app/helpers/multiples_helper.rb",
    "spec/dummy/app/models/confirm.rb",
    "spec/dummy/app/models/image_test.rb",
    "spec/dummy/app/models/multiple.rb",
    "spec/dummy/app/models/multiple_photo.rb",
    "spec/dummy/app/models/paranoid.rb",
    "spec/dummy/app/views/confirms/_form.html.erb",
    "spec/dummy/app/views/confirms/_hidden_form.html.erb",
    "spec/dummy/app/views/confirms/confirm.html.erb",
    "spec/dummy/app/views/confirms/edit.html.erb",
    "spec/dummy/app/views/confirms/index.html.erb",
    "spec/dummy/app/views/confirms/new.html.erb",
    "spec/dummy/app/views/confirms/show.html.erb",
    "spec/dummy/app/views/image_tests/_form.html.erb",
    "spec/dummy/app/views/image_tests/edit.html.erb",
    "spec/dummy/app/views/image_tests/index.html.erb",
    "spec/dummy/app/views/image_tests/new.html.erb",
    "spec/dummy/app/views/image_tests/show.html.erb",
    "spec/dummy/app/views/layouts/application.html.erb",
    "spec/dummy/app/views/multiples/_form.html.erb",
    "spec/dummy/app/views/multiples/edit.html.erb",
    "spec/dummy/app/views/multiples/index.html.erb",
    "spec/dummy/app/views/multiples/new.html.erb",
    "spec/dummy/app/views/multiples/show.html.erb",
    "spec/dummy/config.ru",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/database.yml.example",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/acts_as_image_store.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/image_store.yml.example",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/secret_token.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/locales/en.yml",
    "spec/dummy/config/routes.rb",
    "spec/dummy/db/migrate/20101224074948_create_image_tests.rb",
    "spec/dummy/db/migrate/20110106105927_create_multiples.rb",
    "spec/dummy/db/migrate/20110114060025_create_paranoids.rb",
    "spec/dummy/db/migrate/20110117045843_create_confirms.rb",
    "spec/dummy/public/404.html",
    "spec/dummy/public/422.html",
    "spec/dummy/public/500.html",
    "spec/dummy/public/favicon.ico",
    "spec/dummy/public/javascripts/acts_as_image_store.js",
    "spec/dummy/public/javascripts/application.js",
    "spec/dummy/public/javascripts/jquery-ui.min.js",
    "spec/dummy/public/javascripts/jquery.js",
    "spec/dummy/public/javascripts/jquery_ujs.js",
    "spec/dummy/public/stylesheets/.gitkeep",
    "spec/dummy/public/stylesheets/scaffold.css",
    "spec/dummy/script/rails",
    "spec/helpers/form_builder_spec.rb",
    "spec/helpers/tag_helper_spec.rb",
    "spec/integration/navigation_spec.rb",
    "spec/models/confirm_spec.rb",
    "spec/models/image_test_spec.rb",
    "spec/models/multiple_spec.rb",
    "spec/models/paranoid_spec.rb",
    "spec/models/stored_image_spec.rb",
    "spec/routing_spec.rb",
    "spec/sample.bmp",
    "spec/sample.gif",
    "spec/sample.jpg",
    "spec/sample.png",
    "spec/sample_exif.jpg",
    "spec/sample_huge.gif",
    "spec/spec_helper.rb",
    "spec/storage_adapters_spec.rb",
    "spec/support/backend_helper_methods.rb",
    "spec/support/factories/confirms.rb",
    "spec/support/factories/image_tests.rb",
    "spec/support/factories/multiples.rb",
    "spec/support/factories/paranoids.rb",
    "spec/support/models.rb"
  ]
  s.homepage = %q{http://github.com/mshibuya/acts_as_image_store}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Rails image storage plugin with multiple backend support}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<rmagick>, [">= 0"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_development_dependency(%q<mysql2>, [">= 0"])
      s.add_development_dependency(%q<mogilefs-client>, [">= 0"])
      s.add_development_dependency(%q<sauberia-aws-s3>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.1"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<factory_girl>, [">= 0"])
      s.add_development_dependency(%q<cover_me>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.0.0"])
      s.add_development_dependency(%q<database_cleaner>, [">= 0"])
      s.add_development_dependency(%q<rails3_acts_as_paranoid>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rmagick>, [">= 0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<mysql2>, [">= 0"])
      s.add_dependency(%q<mogilefs-client>, [">= 0"])
      s.add_dependency(%q<sauberia-aws-s3>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.0.1"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<factory_girl>, [">= 0"])
      s.add_dependency(%q<cover_me>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 3.0.0"])
      s.add_dependency(%q<database_cleaner>, [">= 0"])
      s.add_dependency(%q<rails3_acts_as_paranoid>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rmagick>, [">= 0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<mysql2>, [">= 0"])
    s.add_dependency(%q<mogilefs-client>, [">= 0"])
    s.add_dependency(%q<sauberia-aws-s3>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.0.1"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<factory_girl>, [">= 0"])
    s.add_dependency(%q<cover_me>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 3.0.0"])
    s.add_dependency(%q<database_cleaner>, [">= 0"])
    s.add_dependency(%q<rails3_acts_as_paranoid>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
  end
end

